### ISSUE TITLE
Windows - IE Driver does not launch Internet explorer

### ISSUE THREAD

**Issue by gototester** [aerokube/cm#140]
When I run my tests,  I get this error (Below) with the IEDriver.   It works of with Edge annd Chrome though.  I tried reducing the security in the IE setting but it made no difference. 

Logs from selenoid_windows_amd64.exe :
C:\Users\Test User\.aerokube\selenoid>selenoid_windows_amd64.exe -conf browsers.json
2018/03/12 08:26:46 [-] [INIT] [Loading configuration files...]
2018/03/12 08:26:46 [-] [INIT] [Loaded configuration from browsers.json]
2018/03/12 08:26:46 [-] [INIT] [Using default containers log configuration because of: read error: open config/container-logs.json: The system cannot find the path specified.]
2018/03/12 08:26:46 [-] [INIT] [Timezone: Local]
2018/03/12 08:26:46 [-] [INIT] [Video Dir: C:\Users\Test User\.aerokube\selenoid\video]
2018/03/12 08:26:46 [-] [INIT] [Listening on :4444]
2018/03/12 08:27:20 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2018/03/12 08:27:20 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2018/03/12 08:27:20 [0] [LOCATING_SERVICE] [internet explorer] []
2018/03/12 08:27:20 [-] [DEFAULT_VERSION] [Using default version: latest]
2018/03/12 08:27:20 [0] [USING_DRIVER] [internet explorer] [latest]
2018/03/12 08:27:20 [0] [ALLOCATING_PORT]
2018/03/12 08:27:20 [0] [ALLOCATED_PORT] [49972]
2018/03/12 08:27:20 [0] [STARTING_PROCESS] [[C:/Users/Test User/.aerokube/selenoid/IEDriverServer.exe --port=49972]]
2018/03/12 08:27:20 [0] [PROCESS_STARTED] [13940] [0.5385548]
2018/03/12 08:27:20 [0] [PROXY_TO] [http://127.0.0.1:49972]
2018/03/12 08:27:20 [0] [SESSION_ATTEMPTED] [http://127.0.0.1:49972] [1]
2018/03/12 08:27:21 [0] [SESSION_FAILED] [http://127.0.0.1:49972] [Post http://127.0.0.1:49972/session: read tcp 127.0.0.1:49975->127.0.0.1:49972: wsarecv: An existing connection was forcibly closed by the remote host.]
2018/03/12 08:27:21 [0] [TERMINATING_PROCESS] [13940]
2018/03/12 08:27:21 [0] [FAILED_TO_TERMINATE_PROCESS] [13940] [TerminateProcess: Access is denied.]
2018/03/12 08:30:50 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2018/03/12 08:30:50 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2018/03/12 08:30:50 [1] [LOCATING_SERVICE] [chrome] []
2018/03/12 08:30:50 [-] [DEFAULT_VERSION] [Using default version: latest]
2018/03/12 08:30:50 [1] [USING_DRIVER] [chrome] [latest]
2018/03/12 08:30:50 [1] [ALLOCATING_PORT]
2018/03/12 08:30:50 [1] [ALLOCATED_PORT] [50277]
2018/03/12 08:30:50 [1] [STARTING_PROCESS] [[C:/Users/Test User/.aerokube/selenoid/chromedriver.exe --whitelisted-ips="" --verbose --port=50277]]
2018/03/12 08:30:51 [1] [PROCESS_STARTED] [4824] [1.0120772]
2018/03/12 08:30:51 [1] [PROXY_TO] [http://127.0.0.1:50277]
2018/03/12 08:30:51 [1] [SESSION_ATTEMPTED] [http://127.0.0.1:50277] [1]

**Comment by vania-pooh** [comment]
Could you try to launch driver command manually (probably it fails to start for some reason):
```
C:/Users/Test User/.aerokube/selenoid/IEDriverServer.exe --port=49972
```
And then if it starts - try to launch your tests against:
```
http://localhost:49972/
```

**Comment by gototester** [comment]
@vania-pooh  Thans for the speedy response.   I Did as you said.  

Here are the console logs.



C:\Code\e2e-testing-example>"C:/Users/Test User/.aerokube/selenoid/IEDriverServer.exe" --port=49972
Started InternetExplorerDriver server (64-bit)
3.9.0.0
Listening on port 49972
Only local connections are allowed




[11:38:31] I/launcher - Running 1 instances of WebDriver
[11:38:31] I/hosted - Using the selenium server at http://localhost:49972/wd/hub
[11:38:32] E/launcher - Error code: 135
[11:38:32] E/launcher - Error message: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:49972
[11:38:32] E/launcher - Error: ECONNREFUSED connect ECONNREFUSED 127.0.0.1:49972
    at ClientRequest.<anonymous> (C:\Code\e2e-testing-example\node_modules\selenium-webdriver\http\index.js:238:15)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Code\e2e-testing-example\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Code\e2e-testing-example\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Code\e2e-testing-example\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (C:\Code\e2e-testing-example\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Code\e2e-testing-example\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Code\e2e-testing-example\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Code\e2e-testing-example\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Code\e2e-testing-example\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Code\e2e-testing-example\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Code\e2e-testing-example\node_modules\protractor\node_modules\q\q.js:556:49
[11:38:32] E/launcher - Process exited with error code 135

**Comment by vania-pooh** [comment]
Very interesting. You could also try with `--host 127.0.0.1` arg.

**Comment by leeb90** [comment]
I am having this "Access denied" issue but with MicrosoftEdgeDriver, not sure what can be happening.

2018/06/29 09:37:19 [-] [NEW_REQUEST] [unknown] [127.0.0.1]
2018/06/29 09:37:19 [-] [NEW_REQUEST_ACCEPTED] [unknown] [127.0.0.1]
2018/06/29 09:37:19 [0] [LOCATING_SERVICE] [MicrosoftEdge] [42]
2018/06/29 09:37:19 [0] [USING_DRIVER] [MicrosoftEdge] [42]
2018/06/29 09:37:19 [0] [ALLOCATING_PORT]
2018/06/29 09:37:19 [0] [ALLOCATED_PORT] [50639]
2018/06/29 09:37:19 [0] [STARTING_PROCESS] [[C:\Users\Alejandro\Desktop\selenoid\MicrosoftWebDriver.exe --log-level=DEBUG --port=50639]]
2018/06/29 09:37:49 [0] [TERMINATING_PROCESS] [888]
2018/06/29 09:37:49 [0] [FAILED_TO_TERMINATE_PROCESS] [888] [TerminateProcess: Access is denied.]
2018/06/29 09:37:49 [0] [SERVICE_STARTUP_FAILED] [http://127.0.0.1:50639 does not respond in 30s]

I am using webdriverio and this is the error I get when executing the test:

C:\Users\User\Desktop\testexample\node_modules\webdriverio\build\lib\utils\RequestHandler.js:269
                        var errorCode = _constants.ERROR_CODES[body.status] || _constants.ERROR_CODES[body.value.error] || _constants.ERROR_CODES[-1];

TypeError: Cannot read property 'error' of null
    at Request._callback (C:\Users\User\Desktop\testexample\node_modules\webdriverio\build\lib\utils\RequestHandler.js:269:113)
    at Request.self.callback (C:\Users\User\Desktop\testexample\node_modules\webdriverio\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\User\Desktop\testexample\node_modules\webdriverio\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\User\Desktop\testexample\node_modules\webdriverio\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

@gototester , did you find what can be happening? 

Thanks

**Comment by leeb90** [comment]
I was able to make MicrosoftEdge to work, I downloaded the browsers.json with the cm tool to see the differences. Thanks

**Comment by pbetharia123** [comment]
I tried to start the ie driver server from command and got below msg. it did not open IE. what am i missing here.
Started InternetExplorerDriver server (64-bit)
3.11.1.0
Listening on port 5555
Only local connections are allowed

**Comment by vania-pooh** [comment]
@pbetharia123 should open IE only when you request it from tests.

**Comment by pbetharia123** [comment]
I did that too. it says only local connections are allowed.. and then nothing happens.

**Comment by nishhhi** [comment]
Started InternetExplorerDriver server (64-bit)
3.150.1.0
Listening on port 47094
Only local connections are allowed

Even i am facing the same issue

**Comment by hsahib93** [comment]
hi, am having the same issue i have installed the (IEDriverServer.exe) webdriver and put it in the automation testing folder and when i start the server and try to run my test against it, it does not launch and fails the tests.

When i am trying to run it with multiple other browsers with selenium standalone i still face the same issue.
