### ISSUE TITLE
Hybrid mode to use local browser like Safari, with other docker containerized browsers

### ISSUE THREAD

**Issue by m-alzaeem** [aerokube/cm#310]
Hello, 
I'm trying to use Selenoid Configuration Manager to pull all supported browsers docker images, then edit the `browsers.json` file to include `Safari` browser like so:
```
{
  "chrome": {
    "default": "96.0",
    "versions": {
      "96.0": { "image": "selenoid/chrome:96.0", "port": "4444", "path": "/" }
    }
  },
  "firefox": {
    "default": "94.0",
    "versions": {
      "94.0": {
        "image": "selenoid/firefox:94.0",
        "port": "4444",
        "path": "/wd/hub"
      }
    }
  },
  "opera": {
    "default": "81.0",
    "versions": {
      "81.0": { "image": "selenoid/opera:81.0", "port": "4444", "path": "/" }
    }
  },
  "safari": {
    "default": "latest",
    "versions": {
      "latest": {
        "image": ["/usr/bin/safaridriver"],
        "port": "4444"
      }
    }
  }
}
```

my issue is if I run `./cm selenoid configure --browsers-json ./browsers.json` then I don't get Safari working unless I add `--use-drivers` flag, which then results in tests failing on non-Safari browsers :( 

is there a way to let `cm` manages both kind of browsers (in a docker container, and native browsers) at the same time? if not what are other possible solutions?

Thank you!

**Comment by vania-pooh** [comment]
@m-alzaeem there is no such feature. CM is mainly useful for standard scenarios. If you something custom - just update `browsers.json` and use `--browsers-json` flag to sync from your file.

**Comment by m-alzaeem** [comment]
@vania-pooh when using the mentioned above `browsers.json` with the `--browsers-json` flag Safari tests are failing, while Chrome, Firefox, and Opera are passing.
But when using the `--use-drivers` flag, Safari tests pass, while other browsers tests fail.

is the above mentioned `browsers.json` valid for CM? and is there a way to make tests works with all browsers in the `browsers.json` config file?

**Comment by vania-pooh** [comment]
@m-alzaeem your config seems to be correct. What kind of error are you getting with Safari?

**Comment by m-alzaeem** [comment]
@vania-pooh so when running 
`./cm selenoid start --config-dir browsers-config --browsers-json browsers-config/browsers.json`, 
then running my tests on Safari, I get the following error:
```cannot start process [/usr/bin/safaridriver --port=43347]: fork/exec /usr/bin/safaridriver: no such file or directory (RuntimeError)```
and all tests fail.

But if I run Selenoid without CM like so: 
`./selenoid_darwin_amd64 -conf browsers-config/browsers.json`, 
then running my tests against Safari pass, but this solution doesn't play nice with other containerized browsers as they start spinning up more browsers containers after each failed test, which doesn't happen when running CM as it does better job at closing non-used containers.

so my question is: can I use CM with the above `browsers.json`, and run test on local Safari alongside other containerized browsers like Chrome and Firefox? or CM only supports `browsers.json` with browsers in docker images?

**Comment by vania-pooh** [comment]
@m-alzaeem you should start Selenoid as a binary and not in container.

**Comment by m-alzaeem** [comment]
@vania-pooh when using Selenoid as binary and running test on browsers from container like Chrome for example, it spins multiple containers for Chrome and keeps the inactive ones open which then prevents new test from staring and usually end up failing, since the available containers quota is consumed, but this issue doesn't happen when running Selenoid in container using CM

**Comment by vania-pooh** [comment]
@m-alzaeem there is no difference between running Selenoid as a binary and in container. You can compare executable flags with `docker inspect` to get the difference.

**Comment by m-alzaeem** [comment]
so here some output when running Selenoid as binary vs running it using CM:
- when running Selenoid as binary:
`./selenoid_darwin_amd64 -conf browsers-config/browsers.json`
```
 ./selenoid_darwin_amd64 -conf browsers-config/browsers.json
2021/11/24 10:20:21 [-] [INIT] [Loading configuration files...]
2021/11/24 10:20:21 [-] [INIT] [Loaded configuration from browsers-config/browsers.json]
2021/11/24 10:20:21 [-] [INIT] [Video Dir: /Users/m.alzaeem/selenium-grid/video]
2021/11/24 10:20:21 [-] [INIT] [Your Docker API version is 1.41]
2021/11/24 10:20:21 [-] [INIT] [Timezone: Local]
2021/11/24 10:20:21 [-] [INIT] [Listening on :4444]
2021/11/24 10:20:56 [-] [NEW_REQUEST] [unknown] [::1]
2021/11/24 10:20:56 [-] [NEW_REQUEST_ACCEPTED] [unknown] [::1]
2021/11/24 10:20:56 [0] [LOCATING_SERVICE] [chrome] []
2021/11/24 10:20:56 [-] [DEFAULT_VERSION] [Using default version: 96.0]
2021/11/24 10:20:56 [0] [USING_DOCKER] [chrome] [96.0]
2021/11/24 10:20:56 [0] [CREATING_CONTAINER] [selenoid/chrome:96.0]
2021/11/24 10:20:56 [0] [STARTING_CONTAINER] [selenoid/chrome:96.0] [e0e6cd8f3cd27ef21419dd7b13f720f32ec0c50e737e8f2b93264e4d6914ede2]
2021/11/24 10:20:56 [0] [CONTAINER_STARTED] [selenoid/chrome:96.0] [e0e6cd8f3cd27ef21419dd7b13f720f32ec0c50e737e8f2b93264e4d6914ede2] [0.41s]
2021/11/24 10:20:56 http: panic serving [::1]:53456: runtime error: index out of range
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc0003aa000)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1769 +0x139
panic(0x15170a0, 0x19ee740)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/aerokube/selenoid/service.getHostPort.func3(0x15a709f, 0x4, 0xc000304868, 0x8, 0xc0003d9e90, 0xf)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/docker.go:441 +0x188
github.com/aerokube/selenoid/service.getHostPort(0x0, 0x0, 0x0, 0x0, 0x0, 0x15a817f, 0x7, 0x0, 0x0, 0x6fc23ac00, ...)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/docker.go:452 +0x2c7
github.com/aerokube/selenoid/service.(*Docker).StartWithCancel(0xc0003cc000, 0xc000304830, 0x6, 0x0)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/docker.go:197 +0x1a3c
main.create(0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:174 +0x815
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
main.post.func1(0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/gopath/src/github.com/aerokube/selenoid/main.go:258 +0x9a
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
github.com/aerokube/selenoid/protect.(*Queue).Protect.func1(0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:76 +0x36a
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
github.com/aerokube/selenoid/protect.(*Queue).Check.func1(0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:53 +0x90
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
github.com/aerokube/selenoid/protect.(*Queue).Try.func1(0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:35 +0xca
net/http.HandlerFunc.ServeHTTP(0xc00030c1c0, 0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000306300, 0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2375 +0x1d6
main.handler.func1(0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/gopath/src/github.com/aerokube/selenoid/main.go:329 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x15c6298, 0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000a2080, 0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000092820, 0x1664360, 0xc0003b4000, 0xc000344200)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0003aa000, 0x1665860, 0xc000306140)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2884 +0x2f4
2021/11/24 10:20:56 [-] [NEW_REQUEST] [unknown] [::1]
2021/11/24 10:20:56 [-] [NEW_REQUEST_ACCEPTED] [unknown] [::1]
2021/11/24 10:20:56 [1] [LOCATING_SERVICE] [chrome] []
2021/11/24 10:20:56 [-] [DEFAULT_VERSION] [Using default version: 96.0]
2021/11/24 10:20:56 [1] [USING_DOCKER] [chrome] [96.0]
2021/11/24 10:20:56 [1] [CREATING_CONTAINER] [selenoid/chrome:96.0]
2021/11/24 10:20:57 [1] [STARTING_CONTAINER] [selenoid/chrome:96.0] [6e4dce244f689f8ebb91bf24bc5ce435cfca721d3559b2da66eb0a3ecc467c54]
2021/11/24 10:20:57 [1] [CONTAINER_STARTED] [selenoid/chrome:96.0] [6e4dce244f689f8ebb91bf24bc5ce435cfca721d3559b2da66eb0a3ecc467c54] [0.45s]
2021/11/24 10:20:57 http: panic serving [::1]:53461: runtime error: index out of range
goroutine 23 [running]:
net/http.(*conn).serve.func1(0xc00033e460)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1769 +0x139
panic(0x15170a0, 0x19ee740)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/runtime/panic.go:522 +0x1b5
github.com/aerokube/selenoid/service.getHostPort.func3(0xc0002feb3c, 0x4, 0xc0002febc0, 0x8, 0xc00045be50, 0x0)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/docker.go:441 +0x188
github.com/aerokube/selenoid/service.getHostPort(0x0, 0x0, 0x0, 0x0, 0x0, 0x15a817f, 0x7, 0x0, 0x0, 0x6fc23ac00, ...)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/docker.go:450 +0x1c1
github.com/aerokube/selenoid/service.(*Docker).StartWithCancel(0xc0002e9180, 0xc000420660, 0x6, 0x0)
	/home/travis/gopath/src/github.com/aerokube/selenoid/service/docker.go:197 +0x1a3c
main.create(0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/gopath/src/github.com/aerokube/selenoid/selenoid.go:174 +0x815
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
main.post.func1(0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/gopath/src/github.com/aerokube/selenoid/main.go:258 +0x9a
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
github.com/aerokube/selenoid/protect.(*Queue).Protect.func1(0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:76 +0x36a
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
github.com/aerokube/selenoid/protect.(*Queue).Check.func1(0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:53 +0x90
net/http.HandlerFunc.ServeHTTP(...)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995
github.com/aerokube/selenoid/protect.(*Queue).Try.func1(0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/gopath/src/github.com/aerokube/selenoid/protect/queue.go:35 +0xca
net/http.HandlerFunc.ServeHTTP(0xc000363760, 0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0003604c0, 0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2375 +0x1d6
main.handler.func1(0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/gopath/src/github.com/aerokube/selenoid/main.go:329 +0x1c0
net/http.HandlerFunc.ServeHTTP(0x15c6298, 0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000a2080, 0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2375 +0x1d6
net/http.serverHandler.ServeHTTP(0xc000092820, 0x1664360, 0xc0003d6000, 0xc000412300)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc00033e460, 0x1665860, 0xc000360340)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/net/http/server.go:2884 +0x2f4
2021/11/24 10:20:57 [-] [NEW_REQUEST] [unknown] [::1]
2021/11/24 10:20:57 [-] [NEW_REQUEST_ACCEPTED] [unknown] [::1]
2021/11/24 10:20:57 [2] [LOCATING_SERVICE] [chrome] []
2021/11/24 10:20:57 [-] [DEFAULT_VERSION] [Using default version: 96.0]
2021/11/24 10:20:57 [2] [USING_DOCKER] [chrome] [96.0]
2021/11/24 10:20:57 [2] [CREATING_CONTAINER] [selenoid/chrome:96.0]
2021/11/24 10:20:57 [2] [STARTING_CONTAINER] [selenoid/chrome:96.0] [6494d674e4bf80813670b818ed4097be1637d897966779e23d82539b93dc9055]
2021/11/24 10:20:58 [2] [CONTAINER_STARTED] [selenoid/chrome:96.0] [6494d674e4bf80813670b818ed4097be1637d897966779e23d82539b93dc9055] [0.42s]
2021/11/24 10:20:58 [2] [SERVICE_STARTED] [selenoid/chrome:96.0] [6494d674e4bf80813670b818ed4097be1637d897966779e23d82539b93dc9055] [0.60s]
2021/11/24 10:20:58 [2] [PROXY_TO] [6494d674e4bf80813670b818ed4097be1637d897966779e23d82539b93dc9055] [http://127.0.0.1:53467/]
2021/11/24 10:20:58 [2] [SESSION_ATTEMPTED] [http://127.0.0.1:53467/] [1]
2021/11/24 10:20:59 [2] [SESSION_CREATED] [1ed42003a4c094e62daed1b2b0cc3be1] [1] [1.71s]
2021/11/24 10:21:29 [341] [CLIENT_DISCONNECTED] [unknown] [::1] [Error: context canceled]
^C2021/11/24 10:21:31 [-] [SHUTTING_DOWN] [5m0s]
2021/11/24 10:21:31 [2] [REMOVING_CONTAINER] [6494d674e4bf80813670b818ed4097be1637d897966779e23d82539b93dc9055]
2021/11/24 10:21:31 [2] [CONTAINER_REMOVED] [6494d674e4bf80813670b818ed4097be1637d897966779e23d82539b93dc9055]
```

here are the docker containers that it spins up when I run my tests on Chrome:
```
docker ps -a
CONTAINER ID   IMAGE                  COMMAND            CREATED         STATUS         PORTS                                                                                                NAMES
6494d674e4bf   selenoid/chrome:96.0   "/entrypoint.sh"   2 seconds ago   Up 1 second    0.0.0.0:53467->4444/tcp, 0.0.0.0:53468->7070/tcp, 0.0.0.0:53469->8080/tcp, 0.0.0.0:53470->9090/tcp   optimistic_goldstine
6e4dce244f68   selenoid/chrome:96.0   "/entrypoint.sh"   2 seconds ago   Up 1 second    0.0.0.0:53462->4444/tcp, 0.0.0.0:53463->7070/tcp, 0.0.0.0:53464->8080/tcp, 0.0.0.0:53465->9090/tcp   bold_montalcini
e0e6cd8f3cd2   selenoid/chrome:96.0   "/entrypoint.sh"   3 seconds ago   Up 2 seconds   0.0.0.0:53457->4444/tcp, 0.0.0.0:53458->7070/tcp, 0.0.0.0:53459->8080/tcp, 0.0.0.0:53460->9090/tcp   strange_allen
```

here the docker containers left when I shutdown Selenoid binary:
```
docker ps -a
CONTAINER ID   IMAGE                  COMMAND            CREATED          STATUS          PORTS                                                                                                NAMES
6e4dce244f68   selenoid/chrome:96.0   "/entrypoint.sh"   39 seconds ago   Up 38 seconds   0.0.0.0:53462->4444/tcp, 0.0.0.0:53463->7070/tcp, 0.0.0.0:53464->8080/tcp, 0.0.0.0:53465->9090/tcp   bold_montalcini
e0e6cd8f3cd2   selenoid/chrome:96.0   "/entrypoint.sh"   40 seconds ago   Up 39 seconds   0.0.0.0:53457->4444/tcp, 0.0.0.0:53458->7070/tcp, 0.0.0.0:53459->8080/tcp, 0.0.0.0:53460->9090/tcp   strange_allen
```
you can see there are still 2 Chrome containers left that didn't close after shutting down Selenoid binary


- when running Selenoid using CM:
```
./cm_darwin_amd64 selenoid start --browsers-json browsers-config/browsers.json
> Using Docker
- Your Docker API version is 1.41
> Selenoid is already downloaded
> Selenoid is already configured
> Starting Selenoid...
> Successfully started Selenoid
```

here are the containers opened when using CM:
```
docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED          STATUS          PORTS                                    NAMES
0b57d8490737   selenoid/chrome:96.0       "/entrypoint.sh"         10 seconds ago   Up 10 seconds   4444/tcp, 7070/tcp, 8080/tcp, 9090/tcp   hungry_shtern
1db8d331931f   aerokube/selenoid:1.10.7   "/usr/bin/selenoid -…"   55 seconds ago   Up 54 seconds   0.0.0.0:4444->4444/tcp                   selenoid
```

here are the containers left when the test are done or closed
```
docker ps -a
CONTAINER ID   IMAGE                      COMMAND                  CREATED         STATUS         PORTS                    NAMES
1db8d331931f   aerokube/selenoid:1.10.7   "/usr/bin/selenoid -…"   3 minutes ago   Up 3 minutes   0.0.0.0:4444->4444/tcp   selenoid
```
you can see only Selenoid container is left since CM is still running, but most importantly is that all browsers containers are closed properly after the tests are closed and non are left hanging around like in the case when running Selenoid as binary

**Comment by vania-pooh** [comment]
@m-alzaeem sorry, somehow last comment notification got lost. Your stacktrace seems to be the same as https://github.com/aerokube/selenoid/issues/1102 and https://github.com/aerokube/selenoid/issues/1158. Actual reason is that Docker needs so time for ports to allocate. Previously this was working.

**Comment by vania-pooh** [comment]
Closing because of inactivity. Feel free to reopen if still having questions.
